version: "3.8"

services:
  openvpn:
    build: .
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./scripts:/usr/local/bin/scripts
      - openvpn-data:/etc/openvpn

volumes:
  openvpn-data:
